### PR TITLE
Add xlsx (Excel Spreadsheet) support

### PR DESCRIPTION
**Pull request by TheMikaus**
Added Excel spreadsheet support.
Did minor testing with my project.
Also, changed the project files so I could build in VS2017 community edition.

### CODE REVIEW

**Comment by nhmkdev** [comment]
Nice! I'll take a closer look at this in the next week hopefully. I'm using VS 2017 Community Edition too. Wonder why that didn't work for you without changes.

**Comment by TheMikaus** [comment]
> Nice! I'll take a closer look at this in the next week hopefully. I'm using VS 2017 Community Edition too. Wonder why that didn't work for you without changes.

Maybe the removal of the /Y is unnecessary, but I have spaces in my directory names, and that seemed to cause problems.  I'm not sure if that's true, or just some weird artifact of the version of 2017 I'm using (I should probably upgrade again).

**Comment by nhmkdev** [comment]
I ran into a bit of an issue that makes integrating this problematic. I don't have Office installed so I cannot build the project nor could I use the new functionality. It appears I would need to have Microsoft Office installed.

https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-install-office-primary-interop-assemblies?view=vs-2019

https://social.msdn.microsoft.com/Forums/en-US/e4378c7c-fc5e-4d78-9821-c2644c71763f/how-to-use-microsoftofficeinteropexcel-on-a-machine-without-installed-ms-office?forum=exceldev

> You can't use Microsoft.Office.Interop.Excel on a machine where Excel is not installed.

https://github.com/closedxml/closedxml might be a good alternative and you already did a ton of the work! Let me know if that's something you're interested in trying out, otherwise I'd definitely put this on my todo list and take advantage of all the hard work you've done! 👍

**Comment by TheMikaus** [comment]
> I ran into a bit of an issue that makes integrating this problematic. I don't have Office installed so I cannot build the project nor could I use the new functionality. It appears I would need to have Microsoft Office installed.
> 
> https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-install-office-primary-interop-assemblies?view=vs-2019
> 
> https://social.msdn.microsoft.com/Forums/en-US/e4378c7c-fc5e-4d78-9821-c2644c71763f/how-to-use-microsoftofficeinteropexcel-on-a-machine-without-installed-ms-office?forum=exceldev
> 
> > You can't use Microsoft.Office.Interop.Excel on a machine where Excel is not installed.
> 
> https://github.com/closedxml/closedxml might be a good alternative and you already did a ton of the work! Let me know if that's something you're interested in trying out, otherwise I'd definitely put this on my todo list and take advantage of all the hard work you've done! 👍

I'll take a look!  You don't use submodules right?  You just include the code?  I'll also see if I can revert some of the project file changes (like the /Y removal) after I upgrade visual studio.

**Comment by nhmkdev** [comment]
Right, no sub-modules (I've heard a lot of horror stories so I have yet to even consider it in anything I've worked on).

**Comment by TheMikaus** [comment]
Updated to use ClosedXML.
Retested with my project, seemed to work.

**Comment by nhmkdev** [comment]
Thanks! Compiled debug and release without any issues. I'll give this a try with mono in ubuntu sometime soon...

This is a great addition!

**Pull request merged**
