### PR TITLE
Pull request for #131: [Feature Request] Gradient coloring

### PR DESCRIPTION
**Pull request by MarkVabulas**
This is a PR for my solution to #131.  Please check it out.

Added variables for gradients to ProjectLayoutElement.  This is the gradient color, the gradient enable state, and the angle off of horizontal.

This is only enabled for Text objects, since creating a brush object for FormattedText doesn't work (they are per-token brushes, instead of more global). Added bindings so that the values are saved inside the xml files as well as functional in the undo-redo chain. Supplementary added borders around the element color and gradient color panels, so they're more visible.

### CODE REVIEW

**Review by nhmkdev — COMMENTED** [review]
I'll download and give this a try (hopefully over the next couple days).

Couple of quick comments:

- Any idea why the indenting changed? It makes the diff look massive. 😅 
- To make the gradient even more customizable in the future, I would want to consider making it a single raw string field that is split up and interpreted (`gradientdefinition` or something like that). It would make it slightly harder to use but would help avoid adding new fields every time the functionality changes. A wizard dialog could help users build the definition. Thoughts/concerns?

**Comment by MarkVabulas** [comment]
- I think it's possible it auto-converted to CRLF from LF.  
- I only made about 20-40 lines of new code.  Part of the issue with a code change is that moving objects around in the form designer changed all of the coordinates in the other items.  So many many changes were pixel-coordinate updates.
- I like the idea of having it as a single gradient definition, but that's a much larger set of changes that are outside my wheelhouse without a steep learning curve/time investment.  The code to actually do the updates was inside DrawTextGraphics::DrawText lines 86 to 107.  It builds the directionality of the gradient, but the salient information is the creation of a LinearGradientBrush instead of a SolidBrush.  I tried to do the same for DrawFormattedText, but it doesn't work when activated per-sub-element, obviously.

**Comment by nhmkdev** [comment]
This is a cool change! 🥳 I'll look into the necessary adjustments to get this setup as a single field.

I'll investigate using a single string field combined with your changes. All credit to you and your math knowledge on this one (my math understanding is sometimes a bit rough)! 👍

**Comment by nhmkdev** [comment]
While the UI component of the functionality is missing you can specify the gradient inline for now. Submitted change: https://github.com/nhmkdev/cardmaker/commit/7a791f4fb78d384e1ebcb13d372b3790f96a635f

The UI is fairly cramped so I need to decide how to handle adding another field. 🤔 

I added a new section to the [manual ](https://github.com/nhmkdev/cardmaker/blob/master/CardMaker/bin/Release/Card_Maker.odt) as well. Image/instructions from the manual:

gradient_manual

Thanks for doing the graphic research and implementation! I made sure to shout your effort out in the [history ](https://github.com/nhmkdev/cardmaker/blob/master/CardMaker/bin/Release/History.txt) and thank you on the main github page. 👍

**Comment by MarkVabulas** [comment]
This looks good.  Yeah now the UI is the hard part!

**Comment by MarkVabulas** [comment]
Closing the pull request since the functionality has been implemented satisfactorily.

**Comment by MarkVabulas** [comment]
I really like how you used the &[] lookup functionality to do the width/height for the points, pretty classy!

**Pull request closed without merging**
